# Generated by Django 4.0.4 on 2022-04-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=64)),
                ('odraGoal', models.PositiveSmallIntegerField(default=0)),
                ('opponentGoal', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
