# Generated by Django 4.0.4 on 2022-04-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0005_remove_resultofmatch_match_match_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='pictureOfClub',
            field=models.ImageField(blank=True, null=True, upload_to='Logo'),
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='players_picture'),
        ),
    ]
