# Generated by Django 4.0.4 on 2022-04-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0006_club_pictureofclub_player_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='Gol - ', max_length=32, null=True)),
                ('minute', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Oderka.details'),
            preserve_default=False,
        ),
    ]
