# Generated by Django 4.0.4 on 2022-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0007_details_match_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='comment',
            field=models.TextField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
