# Generated by Django 4.0.4 on 2022-04-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0009_remove_match_details_details_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesOfMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='pictures_of_match')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oderka.match')),
            ],
        ),
    ]
