# Generated by Django 4.0.4 on 2022-05-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0010_picturesofmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='match',
        ),
        migrations.AddField(
            model_name='details',
            name='match',
            field=models.ManyToManyField(to='Oderka.match'),
        ),
    ]
