# Generated by Django 4.0.4 on 2022-05-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0011_remove_details_match_details_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='who',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Oderka.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='type',
            field=models.CharField(blank=True, default='Gol', max_length=32, null=True),
        ),
    ]
