# Generated by Django 4.0.4 on 2022-05-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0012_details_who_alter_details_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Oderka.typeofdetails'),
            preserve_default=False,
        ),
    ]
