# Generated by Django 4.0.4 on 2022-05-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0014_club_miniature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
