# Generated by Django 4.0.4 on 2022-05-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0016_details_numberofplayer_alter_match_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='numberOfPlayer',
        ),
        migrations.AddField(
            model_name='player',
            name='numberOfPlayer',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
