# Generated by Django 4.0.4 on 2022-05-19 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0017_remove_details_numberofplayer_player_numberofplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, max_length=516, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Oderka.season'),
            preserve_default=False,
        ),
    ]
