# Generated by Django 4.0.4 on 2022-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0019_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='table',
            name='loses',
        ),
        migrations.RemoveField(
            model_name='table',
            name='wins',
        ),
        migrations.AddField(
            model_name='table',
            name='drawsAway',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='drawsHome',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='losesAway',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='losesHome',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='lostGoalsAway',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='lostGoalsHome',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='shotGoalsAway',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='shotGoalsHome',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='winsAway',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='winsHome',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
