# Generated by Django 4.0.5 on 2022-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0020_remove_table_draws_remove_table_loses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logoOfClub',
            field=models.ImageField(blank=True, null=True, upload_to='Logo'),
        ),
        migrations.AlterField(
            model_name='club',
            name='pictureOfClub',
            field=models.ImageField(blank=True, null=True, upload_to='Picture Of Club'),
        ),
    ]
