# Generated by Django 4.0.5 on 2022-06-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oderka', '0021_club_logoofclub_alter_club_pictureofclub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ManyToManyField(to='Oderka.season'),
        ),
    ]
